---

# Export Vault secret to json file
- name: Export secrets from Vault
  hosts: localhost
  tasks:
  - name: Export secrets from Vault
    ansible.builtin.include_tasks: 
      file: tasks/secrets.yml
    vars:
      action        : export_secrets
      vault_address : "http://192.168.29.20:8200"
      vault_token   : "hvs.9MGoUtPEGZWRgLX3dxZYkqxV"
      vault_name    : "os_template_factory"
      secret_name   :
        - ahv
        - config
        - hyperv
        - rhel8
        - rhel9
        - rockylinux8
        - rockylinux9
        - suse15.5
        - ubuntu20.04
        - ubuntu22.04
        - ubuntu23.04
        - vmware
        - windows10
        - windowsserver2019
        - windowsserver2022
      filename      : "secrets_ostf.json"
