---

# Export Vault secret to json file
- name: Export secrets from Vault
  hosts: localhost
  roles:
   - role: vault
     vars:
      action        : export_secrets
      vault_address : "http://192.168.29.20:8200"
      vault_token   : "hvs.9MGoUtPEGZWRgLX3dxZYkqxV"
      vault_name    : "os_template_factory"
      secret_name   : "windowsserver2022"
      filename      : "secrets_windowsserver2022.json"
