---

# Import json secrets file to Vault
- name: Import secrets from Vault
  hosts: localhost
  tasks:
  - name: Import secrets from Vault
    ansible.builtin.include_tasks: 
      file: tasks/secrets.yml
    vars:
      action        : import_secrets
      vault_address : "http://192.168.29.22:8200"
      vault_token   : "hvs.GiOdZGwlVMPpqZdV0BOMmel6"
      vault_name    : "os_template_factory"
      filename      : "secrets_ostf.json"
