---

#########################################################
## Gather information                                  ##
#########################################################

# Set action_parameters variable to parameter list in actions where key is equal to action
- name: "Gather variables for action ({{ action }})..."
  set_fact:
    action_parameters: "{{ (actions | map('dict2items') | map('first') | selectattr('key', 'equalto', action) | map(attribute='value') | first).parameters }}"

# Validate variables
- name: Validate required variables for action.
  ansible.builtin.assert:
    that: 'item is defined'
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - vault_repository_url

#########################################################
## Pre-installation platform check                     ##
#########################################################

# Determine platform
- name: Determine platform for installation...
  ansible.builtin.include_role:
    name: server-config
  vars:
    action: "platform_check"
  register: platform

#########################################################
## Pre-installation uninstall                          ##
#########################################################

# Run uninstall if uninstall is set
- name: Run uninstall playbook if set
  ansible.builtin.include_tasks: uninstall.yml
  ignore_errors: true
  when: uninstall == true or uninstall is not defined

#########################################################
## Installation on podman                              ##
#########################################################

- name: "Install {{ role_container_name }} container on podman..."
  when: platform == "podman"
  block:

    # Check if podman is detected
    - name: Gather information...
      ansible.builtin.assert:
        that: '"podman" in ansible_facts.packages'
        fail_msg: "Podman is not installed. Please install Podman first. Cannot continue..."

    # Set variable service_user
    - name: Set variable (podman_service_user)...
      ansible.builtin.set_fact:
        podman_service_user: "podman"

    # Get uid of user podman
    - name: "Get uid of user ({{ podman_service_user }})..."
      ansible.builtin.user:
        name: "{{ podman_service_user }}"
      register: podman_service_user_details

    # Set uid of user podman
    - name: "Register uid of user ({{ podman_service_user }})..."
      ansible.builtin.set_fact:
        podman_uid: "{{ podman_service_user_details.uid }}"

    # Create volumes
    - name: Create configuration folders...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: create_volumes
        volume_owner: "{{ podman_service_user }}"
        container_volumes: "{{ vault_container_volumes }}"

    # Create SSL certificate
    - name: Create SSL certificate for Hashicorp Vault...
      ansible.builtin.include_tasks:
        file: create_ssl_certificate.yml
      vars:
        owner: "{{ podman_service_user }}"
        folder: "{{ podman_data_folder}}"

    # Create configuration file
    - name: Create Hashicorp Vault configuration file...
      ansible.builtin.template:
        src: ./templates/vault.podman_config.hcl.j2
        dest: "{{ podman_data_folder }}/vault/config/vault.hcl"
        owner: "{{ podman_service_user }}"

    # Import container
    - name: "Install {{ nexus_container_name }} container on podman"
      ansible.builtin.include_role:
        name: podman
      vars:
        action: import_container
        container_repository_url: "{{ vault_repository_url }}"
        container_repository_tag: "{{ vault_repository_tag | default('latest') }}"
        container_repository_checksum: "{{ vault_repository_checksum }}"
        container_repository_checksum_algorithm: "{{ vault_repository_checksum_algorithm }}"
        container_name: "{{ vault_container_name }}"
        container_ports: "{{ vault_container_ports }}"
        container_volumes: "{{ vault_container_volumes }}"
        container_command: "vault server -config=/vault/config/vault.hcl"
        container_user: "{{ podman_uid }}"
        container_security_opt: ["label=disable"]
        container_privileged: true
        container_cap_add: IPC_LOCK
        container_env: "{{ vault_container_env | default({}) }}"

#########################################################
## Installation on kubernetes                         ##
#########################################################

- name: Install Vault on Kubernetes...
  when: platform == "kubernetes"
  block:

    # Debug message
    - name: Debug message
      ansible.builtin.debug:
        msg: "Install container on kubernetes"

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Installation on host                                ##
#########################################################

- name: Install Vault on host...
  when: platform == "host"
  block:

    # Download Hashicorp Vault from url
    - name: "Download Hashicorp Vault from {{ role_repository_url }}..."
      ansible.builtin.get_url:
        url: "{{ role_repository_url }}"
        dest: "/tmp/{{ role_container_name }}.zip"
        mode: 0755
        validate_certs: false
      register: repository_url_result

    # Unzip Hashicorp Vault
    - name: "Unzip Hashicorp Vault..."
      ansible.builtin.unarchive:
        src: "/tmp/{{ role_container_name }}.zip"
        dest: /usr/local/bin

    # Autostart Vault on system boot
    - name: Generate systemd unit file for Vault...
      ansible.builtin.template:
        src: ./templates/vault.service.j2
        dest: /etc/systemd/system/vault.service
        owner: root
        mode: 0644

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Configuration                                       ##
#########################################################

# Get ip address
- name: Register variable (vault_address)...
  ansible.builtin.set_fact:
    vault_address: "https://{{ ansible_default_ipv4.address }}:{{ vault_container_ports[0].split(':')[0] }}"

# Configure Hashicorp Vault
- name: Configure application
  ansible.builtin.include_tasks: configure.yml
  vars:
    action: configure

#########################################################
## Post-install                                        ##
#########################################################

# Unset variables
#- name: Unset variables
#  ansible.builtin.set_fact:
