---

#########################################################
## Gather information                                  ##
#########################################################

# Set action_parameters variable to parameter list in actions where key is equal to action
- name: "Gather variables for action ({{ action }})..."
  set_fact:
    action_parameters: "{{ (actions | map('dict2items') | map('first') | selectattr('key', 'equalto', action) | map(attribute='value') | first).parameters }}"

# Validate variables
- name: Validate required variables for action.
  ansible.builtin.assert:
    that: 'item is defined'
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - vault_repository_url

#########################################################
## Pre-installation platform check                     ##
#########################################################

# Determine platform
- name: Determine platform for installation...
  ansible.builtin.include_role:
    name: server-config
  vars:
    action: "platform_check"
  register: platform

#########################################################
## Pre-installation uninstall                          ##
#########################################################

# Run uninstall if uninstall is set
- name: Run uninstall playbook if set
  ansible.builtin.include_tasks: uninstall.yml
  ignore_errors: true
  when: uninstall == true or uninstall is not defined

#########################################################
## Installation on podman                              ##
#########################################################

- name: "Install {{ role_container_name }} container on podman..."
  when: platform == "podman"
  block:

    # Check if podman is detected
    - name: Gather information...
      ansible.builtin.assert:
        that: '"podman" in ansible_facts.packages'
        fail_msg: "Podman is not installed. Please install Podman first. Cannot continue..."

    #####################################################
    ## Volume configuration                            ##
    #####################################################

    # Create volumes
    - name: Create configuration folders...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: create_volumes
        container_volumes: "{{ vault_container_volumes }}"
        volume_mode: "0777"

    #####################################################
    ## Vault SSL certificate                           ##
    #####################################################
        
    # Create temp folder for SSL certificate
    - name: Create temporary folder...
      ansible.builtin.file:
        path: "/tmp/vault/certs"
        state: directory
  
    # Create SSL certificate
    - name: Create SSL certificate for Hashicorp Vault...
      ansible.builtin.include_tasks:
        file: create_ssl_certificate.yml
      vars:
        destination_folder: "/tmp/vault/certs" 
 
    # Copy SSL certificate to container
    - name: Copy SSL certificate to container volume...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: copy_to_volume
        volume_source_folder: "/tmp/vault/certs/"
        volume_destination_folder: "/vault/config"
        volume_mode: "0777"

    # Delete temp folder
    - name: Delete temporary folder...
      ansible.builtin.file:
        path: "/tmp/vault/certs"
        state: absent

    #####################################################
    ## Vault configuration                             ##
    #####################################################    
    
    # Create temp folder for configuration file
    - name: Create temporary folder...
      ansible.builtin.file:
        path: "/tmp/vault"
        state: directory

    # Create configuration file
    - name: Create Hashicorp Vault configuration file...
      ansible.builtin.template:
        src: ./templates/vault.podman_config.hcl.j2
        dest: "/tmp/vault/vault.hcl"

    # Copy configuration file to container
    - name: Copy configuration file to container...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: copy_to_volume
        volume_source_folder: "/tmp/vault/"
        volume_destination_folder: "/vault/config"
        volume_mode: "0777"

    # Delete temp folder
    - name: Delete temporary folder...
      ansible.builtin.file:
        path: "/tmp/vault"
        state: absent

    #####################################################
    ## Firewall configuration                          ##
    #####################################################

    # Open firewall ports
    - name: Open firewall ports...
      become: true
      ansible.posix.firewalld:
        port: "{{ vault_container_ports[0].split(':')[0] }}/tcp"
        permanent: true
        state: enabled
        immediate: true

    #####################################################
    ## Import container                                ##
    #####################################################

    # Import container
    - name: "Install {{ vault_container_name }} container on podman"
      ansible.builtin.include_role:
        name: podman
      vars:
        action: import_container
        container_repository_url: "{{ vault_repository_url }}"
        container_repository_tag: "{{ vault_repository_tag | default('latest') }}"
        container_repository_checksum: "{{ vault_repository_checksum }}"
        container_repository_checksum_algorithm: "{{ vault_repository_checksum_algorithm }}"
        container_name: "{{ vault_container_name }}"
        container_ports: "{{ vault_container_ports }}"
        container_volumes: "{{ vault_container_volumes }}"
        container_command: "vault server -config=/vault/config/vault.hcl"
        container_security_opt: ["label=disable"]
        container_cap_add: IPC_LOCK
        container_env: "{{ vault_container_env | default({}) }}"

#########################################################
## Installation on kubernetes                         ##
#########################################################

- name: Install Vault on Kubernetes...
  when: platform == "kubernetes"
  block:

    # Debug message
    - name: Debug message
      ansible.builtin.debug:
        msg: "Install container on kubernetes"

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Installation on host                                ##
#########################################################

- name: Install Vault on host...
  when: platform == "host"
  block:

    # Download Hashicorp Vault from url
    - name: "Download Hashicorp Vault from {{ vault_repository_url }}..."
      ansible.builtin.get_url:
        url: "{{ vault_repository_url }}"
        dest: "/tmp/{{ vault_container_name }}.zip"
        mode: 0755
        validate_certs: false
      register: repository_url_result

    # Unzip Hashicorp Vault
    - name: "Unzip Hashicorp Vault..."
      ansible.builtin.unarchive:
        src: "/tmp/{{ vault_container_name }}.zip"
        dest: /usr/local/bin

    # Autostart Vault on system boot
    - name: Generate systemd unit file for Vault...
      ansible.builtin.template:
        src: ./templates/vault.service.j2
        dest: /etc/systemd/system/vault.service
        owner: root
        mode: 0644

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Configuration                                       ##
#########################################################

# Get ip address
- name: Register variable (vault_address)...
  ansible.builtin.set_fact:
    vault_address: "https://{{ ansible_default_ipv4.address }}:{{ vault_container_ports[0].split(':')[0] }}"

# Configure Hashicorp Vault
- name: Configure application
  ansible.builtin.include_tasks: configure.yml
  vars:
    action: configure

#########################################################
## Post-install                                        ##
#########################################################

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    vault_repository_url: null
    vault_repository_tag: null
    vault_repository_checksum: null
    vault_repository_checksum_algorithm: null
    vault_container_name: null
    vault_container_ports: null
    vault_container_volumes: null
    vault_container_env: null
    vault_container_user: null
    vault_container_user_details: null
    vault_container_user_uid: null
