---

#########################################################
## Destroy Secret                                      ##
#########################################################

- name: Destroy Vault secret
  when: action == "destroy_secret"
  block:
  
    # Validate local variables
    - name: Validate variables for Vault destroy_secret action.
      ansible.builtin.assert:
        that: "varitem is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop: 
        - vault_name
        - secret_name

    # TODO