---

#########################################################
## Create Secret                                       ##
#########################################################

- name: Create Vault secret
  when: action == "create_secret"
  block:

    # Validate local variables
    - name: Validate variables for Vault create_secret action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop: 
        - vault_name
        - secret_name

    # Create secret via API. Authenticate with vault_token.
    - name: "Create secret {{ secret_name }} via API"
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/{{ vault_name }}/data/{{ secret_name }}"
        validate_certs: false 
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body: 
          data: "{{ secret_keyvalue }}"
      register: vault_secret
      no_log: true