---

#########################################################
## Hashicorp Vault Secret Engine module                ##
#########################################################

# Validate global variables for Hashicorp Vault secret_engine module.
- name: Validate variables for Hashicorp Vault secret_engine module.
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop: 
    - vault_address
    - vault_token
    - vault_type

#########################################################
## Select Secrets Engine type                          ##
#########################################################

# include task if vault_type is kv
- name: Include KV secret engine...
  ansible.builtin.include_tasks: secret_engine_kv.yml
  when: vault_type == 'kv'

# include task if vault_type is pki
- name: Include PKI secret engine...
  ansible.builtin.include_tasks: secret_engine_pki.yml
  when: vault_type == 'pki'

# include task if vault_type is ssh
- name: Include SSH secret engine...
  ansible.builtin.include_tasks: secret_engine_ssh.yml
  when: vault_type == 'ssh'
