---

# Show information message
- name: Information message
  ansible.builtin.debug:
    msg: "This part is not (yet) implemented."

# Stop playbook
- name: Stop playbook
  ansible.builtin.meta: end_play
  