---

#########################################################
## Uninstall action                                    ##
#########################################################
# Uninstall action 
# variables: 
#   - vault_container_name: Name of the container to uninstall
#   - vault_container_volumes: Volumes folders of the container to uninstall
#   - keep_data: true/false. Keep data when uninstalling. Default false.

#########################################################
## Uninstall configuration                             ##
#########################################################

# Set keep_data if not defined
- name: Set keep_data if not defined
  set_fact:
    keep_data: false
  when: keep_data is not defined
  
#########################################################
## Uninstall via podman                                ##
#########################################################

- name: "Uninstall {{ vault_vars.container.name }} on podman"
  when: platform == "podman"
  block:

    # Check if container is present
    - name: Check if container is present
      containers.podman.podman_container_info:
        name: "{{ vault_vars.container.name }}"
      register: pod_info
      ignore_errors: true

    # Remove container
    - name: "Remove container {{ vault_vars.container.name }}"
      containers.podman.podman_container:
        name: "{{ vault_vars.container.name }}"
        state: absent
      when: pod_info is defined

#########################################################
## Uninstall via kubernetes                            ##
#########################################################

- name: "Uninstall {{ vault_vars.container.name }} on kubernetes"
  when: platform == "kubernetes"
  block:

    # show debug message
    - name: Debug message
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Uninstall via host                                  ##
#########################################################

- name: "Uninstall application on host"
  when: platform == "host"
  block:

    # Show information message
    - name: Information message
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Uninstall data                                      ##
#########################################################

# Start destroy_volumes from podman role
- name: "Destroy container data folders for {{ vault_vars.container.name }}..."
  ansible.builtin.include_role:
    name: podman
  vars:
    action: destroy_volumes
    container_volumes: "{{ vault_vars.container.volumes }}"
  when:
    - platform == "podman"
    - keep_data == false

#########################################################
## Uninstall users/groups                              ##
#########################################################

# TODO

#########################################################
## Post-uninstall                                      ##
#########################################################

# Unset variables
- name: Unset variables
  set_fact:
    keep_data: null

