---

# Export Vault secret to json file example
- name: Export secrets from Vault
  hosts: localhost
  vars:
    vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=Undefined) }}"

  tasks:
  - name: Export secrets from Vault
    ansible.builtin.include_role:
      name: vault
    vars:
      action : export_secrets
      # vault_address : "" # set in environment variable
      # vault_token   : "" # set in environment variable
      vault_name    : "cisco-callmanager"
      secret_name   : "UCM-42M0001"
      filename      : "secrets_cisco_callmanager.json"
