---

# Export Vault secrets to file example
- name: Export secrets from Vault
  hosts: localhost
  vars:
    vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=Undefined) }}"

  tasks:
  - name: Export secrets from Vault
    ansible.builtin.include_role:
      name: vault
    vars:
      action : export_secrets
      # vault_address : "" # set in environment variable
      # vault_token   : "" # set in environment variable
      # secret_engine_name : # set in secrets variable
      # secret_name        : # set in secrets variable
      filename : "secrets_export1"
      secrets  : |
        [
          {
            "secret_engine_name": "cisco-callmanager",
            "secret_name": "localhost-localdomain"
          },
          {
            "secret_engine_name": "hashicorp-vault",
            "secret_name": "localhost-localdomain"
          },
          {
            "secret_engine_name": "nexus-repository",
            "secret_name": "10-42-1-200"   
          },
          {
            "secret_engine_name": "nutanix-ahv",
            "secret_name": "10-42-1-55"
          },
          {
            "secret_engine_name": "nutanix-ahv",
            "secret_name": "os-templates"
          },
          {
            "secret_engine_name": "vmware-vsphere",
            "secret_name": "localhost-localdomain"
          },          
          {
            "secret_engine_name": "vmware-vsphere",
            "secret_name": "os-templates"
          }
        ]
