---

# Export Vault secrets to file example
- name: Export secrets from Vault
  hosts: localhost
  vars:
    vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=Undefined) }}"

  tasks:
  - name: Export secrets from Vault
    ansible.builtin.include_role:
      name: vault
    vars:
      action : export_secrets
      # vault_address : "" # set in environment variable
      # vault_token   : "" # set in environment variable
      filename           : "secrets_export2"
      secret_engine_name : "cisco-callmanager"
      secret_name        : "localhost-localdomain"
      # secrets  : |
      #  [
      #    {
      #      "secret_engine_name": "cisco-callmanager",
      #      "secret_name": "localhost-localdomain"
      #    }]
   