---

# Import Vault secrets export file
- name: Import secrets from file into Vault
  hosts: localhost
  vars:
    vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=Undefined) }}"

  tasks:
  - name: Import secrets from file into Vault
    ansible.builtin.include_role:
      name: vault
    vars:
      action : import_secrets
      # vault_address : "" # set in environment variable
      # vault_token   : "" # set in environment variable
      filename : "~/server-PSP/secrets_export1.zip"
