---

#########################################################
## Hashicorp Vault SSH Secret Engine module            ##
#########################################################

#########################################################
## Get SSH Secrets engine                              ##
#########################################################

# Get Hashicorp Vault secret engine SSH
- name: get_secret_engine action...
  when: action == 'get_secret_engine'
  block:

    # Register var_result variable
    - name: Register var_result variable
      ansible.builtin.set_fact:
        var_result: "{{ var_result }}"
      no_log: true
      when: var_result is not defined

    # Clear variable var_result, be sure it is not used from a previous run.
    - name: Clear variable var_result
      ansible.builtin.set_fact:
        var_result: ""
      no_log: true

    # Validate local variables
    - name: Validate variables for Vault get_secret_engine action.
      ansible.builtin.assert:
        that: "varitem is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - secret_engine_name

    # TODO

    # Show information message
    - name: "This part is not (yet) implemented."
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Create SSH Secrets engine                           ##
#########################################################

# Create Hashicorp Vault secret engine SSH
- name: Create Vault KV secret engine
  when: action == 'create_secret_engine'
  block:

  # Validate variables
    - name: Validate variables for Vault create_secret_engine action.
      ansible.builtin.assert:
        that: "varitem is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - secret_engine_name
        - secret_engine_description

    # Create Hashicorp secrets engine via api. Authenticate with vault_token.
    - name: Create Hashicorp secrets engine via api
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/mounts/{{ secret_engine_name }}"
        validate_certs: "{{ vault_vars.application.validate_certs | default(true) }}"
        method: POST
        status_code: 204
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          type: ssh
          description: "{{ secret_engine_description }}"

  # Error handling when error occured.
  rescue:

    # TODO

    # Show information message
    - name: "Information message"
      ansible.builtin.debug:
        msg: "An error occured. Cannot continue..."

#########################################################
## Destroy KV Secrets engine                           ##
#########################################################

# Destroy Hashicorp Vault secret engine SSH
- name: Destroy Vault SSH secret engine
  when: action == 'destroy_secret_engine'
  block:

  # Validate local variables
    - name: Validate variables for Vault destroy_secret_engine action.
      ansible.builtin.assert:
        that: "varitem is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - secret_engine_name

    # Destroy Hashicorp secrets engine via api. Authenticate with vault_token.
    - name: "Destroy Hashicorp secrets engine {{ secret_engine_name }}"
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/mounts/{{ secret_engine_name }}"
        validate_certs: "{{ vault_vars.application.validate_certs | default(true) }}"
        method: DELETE
        status_code: 204
        headers:
          X-Vault-Token: "{{ vault_token }}"

  # Error handling when error occured.
  rescue:

    # TODO

    # Show information message
    - name: "Information message"
      ansible.builtin.debug:
        msg: "An error occured. Cannot continue..."

#########################################################
## Post-actions                                        ##
#########################################################

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    vault_result: ""
