---

#########################################################
## Hashicorp Vault Destroy Secret module               ##
#########################################################

# Validate variables for Hashicorp Vault secrets module.
- name: Validate variables for Hashicorp Vault secrets module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - vault_address
    - vault_token

# Show information message
- name: Information message
  ansible.builtin.debug:
    msg: "This part is not (yet) implemented."

# Stop playbook
- name: Stop playbook
  ansible.builtin.meta: end_play
