---

#########################################################
## Export secret helper module                         ##
#########################################################

# Get secret via Vault API.
- name: Retrieve secrets from Vault...
  ansible.builtin.uri:
    url: "{{ vault_address }}/v1/{{ secret_engine_name }}/data/{{ item }}"
    validate_certs: "{{ vault_validate_certs | default(true) }}"
    method: GET
    headers:
      X-Vault-Token: "{{ vault_token }}"
    return_content: yes
  register: secret_response
  no_log: true

# Set result
- name: Add secrets to file...
  ansible.builtin.set_fact:
    secret_results: '{{ secret_results }} + [{ "secret_name": "{{ item }}", "hash": {{ secret_response.json.data.data | hash("sha256") }}, "secret_data": {{ secret_response.json.data.data }} }]'
  no_log: true
