---

#########################################################
## Export secret helper module                         ##
#########################################################

# Get secret via Vault API.
- name: Retrieve secrets from Vault...
  ansible.builtin.uri:
    url: "{{ vault_address }}/v1/{{ secret.secret_engine_name }}/data/{{ secret.secret_name }}"
    validate_certs: "{{ vault_vars.application.validate_certs | default(true) }}"
    method: GET
    headers:
      X-Vault-Token: "{{ vault_token }}"
    return_content: yes
  register: secret_response
  no_log: true

# Set variable
- name: Set secret_results variable...
  ansible.builtin.set_fact:
    secret_results_item:
      secret_engine_name: "{{ secret.secret_engine_name }}"
      secret_name: "{{ secret.secret_name }}"
      hash: "{{ secret_response.json.data.data | hash('sha256') }}"
      secret_data: "{{ secret_response.json.data.data }}"

# Initialize secret_results if not already initialized
- name: Initialize secret_results variable...
  ansible.builtin.set_fact:
    secret_results: "{{ secret_results | default([]) | list }}"

# Set result
- name: Add secrets to variable...
  ansible.builtin.set_fact:
    secret_results: "{{ secret_results + [secret_results_item] }}"
  no_log: true

# Debug message
- name: Information message...
  ansible.builtin.debug:
    msg: "Secret {{ secret.secret_name }} retrieved from secret engine {{ secret.secret_engine_name }}..."
