---

#########################################################
## Hashicorp Vault Export Secrets module               ##
#########################################################

# Validate variables for Hashicorp Vault secrets module.
- name: Validate variables for Hashicorp Vault secrets module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - vault_address
    - vault_token

# Validate local variables
- name: Validate required variables for Vault export_secrets action...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - secret_engine_name
    - secret_name
    - filename

# Register variable, clear results
- name: Register variable (secret_results)
  ansible.builtin.set_fact:
    secret_results: ""

# # loop through secrets, get secrets from Vault
- name: Include task
  ansible.builtin.include_tasks: export_secrets_helper.yml
  loop: "{{ secret_name }}"

# Parse secret_results JSON
- name: Parse secret results...
  ansible.builtin.set_fact:
    secret_export:  '{ "secrets": {{ secret_results }}, "filename": "{{ filename }}", "timestamp": "{{ ansible_date_time.iso8601 }}", "user": "{{ ansible_user_id }}" }'

# Write secret to file
- name: Write secret to file
  ansible.builtin.copy:
    content: "42{{ secret_export | to_nice_json | b64encode }}"
    dest: "{{ filename }}.json"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600

# archive json file
- name: Archive json file
  community.general.archive:
    path: "{{ filename }}.json"
    dest: "{{ filename }}.tar.gz"
    format: gz

# Remove json file
- name: Remove json file
  ansible.builtin.file:
    path: "{{ filename }}.json"
    state: absent

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    secret_result: null
    secret_export: null
