---

#########################################################
## Import secret helper module                         ##
#########################################################

# Create secret_engine_name, will skip if already exists
- name: Create secret engine {{ item.secret_engine_name }}...
  ansible.builtin.include_tasks: secret_engine/secret_engine.yml
  vars:
    action: create_secret_engine
    secret_engine_name: "{{ item.secret_engine_name }}"
    secret_engine_description: ""
    secret_engine_type: "kv"

# Create secret 
- name: Create secret {{ item.secret_name }}...
  ansible.builtin.include_tasks: create_secret.yml
  vars:
    action: create_secret
    secret_engine_name: "{{ item.secret_engine_name }}"
    secret_name: "{{ item.secret_name }}"
    secret_keyvalue: "{{ item.secret_data | from_yaml }}"

# Debug message
- name: Information message...
  ansible.builtin.debug:
    msg: "Secret {{ item.secret_name }} stored in secret engine {{ item.secret_engine_name }}..."
